services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
      - composer_cache:/tmp/composer
    working_dir: /var/www/html
    environment:
      - COMPOSER_CACHE_DIR=/tmp/composer
    stdin_open: true
    tty: true
    command: sh

volumes:
  composer_cache:
